Import Libraries

In [1]:
import os
import cv2
import numpy as np
from imutils import paths
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset,Dataset
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_curve

In [23]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

link of the animals dataset 
https://drive.google.com/file/d/1wOMljDQMRgh3QjtnbOliyWtQFhH0mGn0/view?usp=share_link

#Class to load the dataset images from drive

In [24]:

class SimpleDatasetLoader:
    # Method: Constructor
    def __init__(self, preprocessors=None):
        """
        :param preprocessors: List of image preprocessors
        """
        self.preprocessors = preprocessors

        if self.preprocessors is None:
            self.preprocessors = []

    # Method: Used to load a list of images for pre-processing
    def load(self, image_paths, verbose=-1):
        """
        :param image_paths: List of image paths
        :param verbose: Parameter for printing information to console
        :return: Tuple of data and labels
        """
        data, labels = [], []

        for i, image_path in enumerate(image_paths):
            image = cv2.imread(image_path)
            label = image_path.split(os.path.sep)[-2]

            if self.preprocessors is not None:
                for p in self.preprocessors:
                    image = p.preprocess(image)

            data.append(image)
            labels.append(label)

            if verbose > 0 and i > 0 and (i+1) % verbose == 0:
                print('[INFO]: Processed {}/{}'.format(i+1, len(image_paths)))

        return (np.array(data), np.array(labels))

In [25]:
#Class Preprocessror 
class SimplePreprocessor:
    # Method: Constructor
    def __init__(self, width, height, interpolation=cv2.INTER_AREA):
        """
        :param width: Image width
        :param height: Image height
        :param interpolation: Interpolation algorithm
        """
        self.width = width
        self.height = height
        self.interpolation = interpolation

    # Method: Used to resize the image to a fixed size (ignoring the aspect ratio)
    def preprocess(self, image):
        """
        :param image: Image
        :return: Re-sized image
        """
        return cv2.resize(image, (self.width, self.height), interpolation=self.interpolation)

In [26]:
from __main__ import SimplePreprocessor
from __main__ import SimpleDatasetLoader

In [27]:
image_paths = list(paths.list_images("animals"))

# Initialize SimplePreprocessor and SimpleDatasetLoader and load data and labels
print('[INFO]: Images loading....')
sp = SimplePreprocessor(32, 32)
sdl = SimpleDatasetLoader(preprocessors=[sp])
(data, labels) = sdl.load(image_paths, verbose=500)

# Reshape from (3000, 32, 32, 3) to (3000, 32*32*3=3072)
data = data.reshape((data.shape[0], 3072))

# Print information about memory consumption
print('[INFO]: Features Matrix: {:.1f}MB'.format(float(data.nbytes / 1024*1000.0)))

# Encode labels as integers
le = LabelEncoder()
labels = le.fit_transform(labels)

# Split data into training (75%) and testing (25%) data
X_train, X_test, y_train, y_test= train_test_split(data, labels, test_size=0.25, random_state=42)

[INFO]: Images loading....
[INFO]: Processed 500/3000
[INFO]: Processed 1000/3000
[INFO]: Processed 1500/3000
[INFO]: Processed 2000/3000
[INFO]: Processed 2500/3000
[INFO]: Processed 3000/3000
[INFO]: Features Matrix: 9000000.0MB


In [28]:
X_train.shape

(2250, 3072)

In [29]:
class class_dataset(Dataset):
    pass
# code here

In [ ]:
class SimpleClassificationNet(torch.nn.Module):
            
    def __init__(self):
        super().__init__()        
#         code here


    def forward(self,x):
#        code here
        return y_hat

In [2]:
#Preparing PyTorch DataSets and DataLoaders

# Builds tensors from numpy arrays

# code here

# Builds dataset containing ALL data points

#     code here

# Builds a loader of each set
# code here

In [39]:
#model, optimizer and loss
model = SimpleClassificationNet().to(device)
stateDict=model.state_dict()


lr = 0.001
#  define optimizor here
# define loss here

In [40]:
#batch wise training loop
epochs = 100
train_losses = []
val_losses = []
best_accuracy=0
for epoch in range(epochs):  #epochs loop

    all_Y_train_epoch=np.array([]).reshape(0,1)
    all_Yhat_train_epoch=np.array([]).reshape(0,1)
    all_train_losses_epoch=np.array([])

    for X_train, Y_train in train_loader:        #batch wise  training on train set
        model.train()
#         forward pass
        
    
#     backward passs
        
        #store metrics for all batches of current epoch 
        y_hat=F.softmax(logits,dim=-1)
        y_hat=y_hat.detach().cpu().numpy()
        y_hat=np.argmax(y_hat,axis=1)
        y_hat=y_hat.reshape(-1,1)

        Y_train=Y_train.detach().cpu().numpy()
        Y_train=Y_train.reshape(-1,1)
        all_Y_train_epoch=np.vstack((all_Y_train_epoch,Y_train))
        all_Yhat_train_epoch=np.vstack((all_Yhat_train_epoch,y_hat))   
        all_train_losses_epoch=np.append(all_train_losses_epoch,loss.item())     
        
    
    
    #computing metrics for current epoch
    train_losses.append(all_train_losses_epoch.mean()) #mean loss for all batches    
    acTrain=accuracy_score(all_Y_train_epoch, all_Yhat_train_epoch)
    cmTrain=confusion_matrix(all_Y_train_epoch, all_Yhat_train_epoch)
    print(cmTrain)

    #validation loop also bacth wise
    all_Y_val_epoch=np.array([]).reshape(0,1)
    all_Yhat_val_epoch=np.array([]).reshape(0,1)
    all_val_losses_epoch=np.array([])
    for X_val, Y_val in val_loader:  #batch wise validation set predictions only
        model.eval()
        
        X_val = X_val.to(device)
        Y_val = Y_val.to(device)
        
        with torch.no_grad():            
            logits = model(X_val)           
            loss = loss_fn(logits, Y_val)
        
        #store metrics for all batches of current epoch 
        y_hat_val=F.softmax(logits,dim=-1)
        y_hat_val=y_hat_val.detach().cpu().numpy()
        y_hat_val=np.argmax(y_hat_val,axis=1)
        y_hat_val=y_hat_val.reshape(-1,1)
        Y_val=Y_val.detach().cpu().numpy()
        Y_val=Y_val.reshape(-1,1)
        all_Y_val_epoch=np.vstack((all_Y_val_epoch,Y_val))
        all_Yhat_val_epoch=np.vstack((all_Yhat_val_epoch,y_hat_val))   
        all_val_losses_epoch=np.append(all_val_losses_epoch,loss.item())     
            

    #computing metrics for current epoch
    val_losses.append(all_val_losses_epoch.mean()) #mean loss for all batches    
    acVal=accuracy_score(all_Y_val_epoch, all_Yhat_val_epoch)
    cmVal=confusion_matrix(all_Y_val_epoch, all_Yhat_val_epoch)
    
    print(f"epoch= {epoch}, accuracyTrain= {acTrain}, accuracyVal= {acVal}, train_loss= {train_losses[epoch]}, validation_loss= {val_losses[epoch]}")
    
    #checkpointing training
    if(acVal>best_accuracy):
        checkpoint = {'epoch': epoch,'model_state_dict': model.state_dict(),
                      'optimizer_state_dict': optimizer.state_dict(),'loss': train_losses,
                      'val_loss': val_losses}
        torch.save(checkpoint,'best.pth')



#loading best model
checkpoint = torch.load('best.pth')
# Restore state for model and optimizer
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
total_epochs = checkpoint['epoch']
losses = checkpoint['loss']
val_losses = checkpoint['val_loss']

[[3 2 0]
 [2 0 0]
 [2 1 0]]
epoch= 0, accuracyTrain= 0.3, accuracyVal= 0.332, train_loss= 6.019345283508301, validation_loss= 48.17238212585449
[[0 5 0]
 [0 2 0]
 [0 3 0]]
epoch= 1, accuracyTrain= 0.2, accuracyVal= 0.31866666666666665, train_loss= 54.71075439453125, validation_loss= 147.1113082885742
[[0 0 5]
 [0 0 2]
 [0 0 3]]
epoch= 2, accuracyTrain= 0.3, accuracyVal= 0.34933333333333333, train_loss= 84.30062103271484, validation_loss= 863.9289518229167
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 3, accuracyTrain= 0.5, accuracyVal= 0.34933333333333333, train_loss= 709.9057006835938, validation_loss= 9.703746376037598
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 4, accuracyTrain= 0.5, accuracyVal= 0.31866666666666665, train_loss= 7.811806678771973, validation_loss= 11.023172143300375
[[0 0 5]
 [0 0 2]
 [0 0 3]]
epoch= 5, accuracyTrain= 0.3, accuracyVal= 0.37066666666666664, train_loss= 12.104036331176758, validation_loss= 1.1829553731282552
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 6, accuracyTrain= 0.5, accur

epoch= 55, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.0658589601516724, validation_loss= 1.1828002349535625
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 56, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.0658278465270996, validation_loss= 1.1827974899609883
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 57, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.0657968521118164, validation_loss= 1.1827946710586548
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 58, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.0657659769058228, validation_loss= 1.1827920651435853
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 59, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.065735101699829, validation_loss= 1.1827892804145812
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 60, accuracyTrain= 0.5, accuracyVal= 0.37066666666666664, train_loss= 1.065704107284546, validation_loss= 1.1827865703900655
[[5 0 0]
 [2 0 0]
 [3 0 0]]
epoch= 61, accuracyTrain= 0.5, accur

In [ ]:
# plot the losses here